# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast observation error function continuous
NULL

#' @export
kinetics_power_function_cpp <- function(times, pars) {
    .Call('_jahR_kinetics_power_function_cpp', PACKAGE = 'jahR', times, pars)
}

likelihood_func_fast_continuous <- function(theta, obs, predicted_titres) {
    .Call('_jahR_likelihood_func_fast_continuous', PACKAGE = 'jahR', theta, obs, predicted_titres)
}

