# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kinetics_power_function_cpp <- function(times, pars) {
    .Call('_jahR_kinetics_power_function_cpp', PACKAGE = 'jahR', times, pars)
}

